### ISSUE TITLE
[공통] API 요청, 응답 형식 조회를 위한 Swagger UI 를 적용한다.

### ISSUE THREAD

**Issue by domo7304** [2022-mwomeokji/2022-MMG#38]
## 작업내용
API 요청, 응답 조회를 위한 Swagger UI 적용
## 상세 내용
API 요청, 응답에 대한 json 값을 조회하기 위해 Swagger UI 를 이용하여 API 문서화 진행

**Comment by minseong0609** [comment]
Swagger UI 는 postman에서 하는 그거인가요?

**Comment by domo7304** [comment]
> 

<a href=https://jojoldu.tistory.com/31>Swagger로 API 문서 자동화하기</a> - 여기 링크에서 구현적인 부분은 건너뛰고 '3. Swagger-ui 확인' 이 쯤에서부터 보면 될 거 같은데

1. 어떤 API 들이 있는지
2. API request 에 어떤 값들을 담아 보내야 하는지
3. response 로는 어떤 값들이 반환되는지
4. postman처럼 실제 테스트도 해볼 수 있음

이런 기능을 하는 도구고, API 문서화를 위해서 적용해주는 거라고 생각하며 될 거 같아
